# Generated by Django 4.2.30 on 2026-07-03 16:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='queued', max_length=50)),
                ('outcome', models.CharField(default='pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('duration_sec', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel_type', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(db_column='campaign_id', on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'db_table': 'calls',
            },
        ),
        migrations.CreateModel(
            name='CallTranscript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.OneToOneField(db_column='call_id', on_delete=django.db.models.deletion.CASCADE, to='calls.call')),
            ],
            options={
                'db_table': 'call_transcripts',
            },
        ),
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_url', models.TextField(default='/audio/sample-recording.wav')),
                ('duration_sec', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.OneToOneField(db_column='call_id', on_delete=django.db.models.deletion.CASCADE, to='calls.call')),
            ],
            options={
                'db_table': 'call_recordings',
            },
        ),
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(db_column='call_id', on_delete=django.db.models.deletion.CASCADE, to='calls.call')),
            ],
            options={
                'db_table': 'call_events',
            },
        ),
    ]
