# Generated by Django 4.2.30 on 2026-08-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
