# Generated by Django 4.2.30 on 2026-08-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_call_next_retry_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='twilio_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='recording_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
