# Generated by Django 4.2.30 on 2026-07-03 16:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(default='en', max_length=50)),
                ('tags', models.TextField(default='')),
                ('notes', models.TextField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('customer_type', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('custom_fields', models.TextField(blank=True, null=True)),
                ('consent_status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(db_column='business_id', on_delete=django.db.models.deletion.CASCADE, to='receptify.business')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
