# Generated by Django 4.2.30 on 2026-07-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
