# Generated by Django 4.2.30 on 2026-07-09 17:18

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import uuid


def migrate_tags_to_array(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    for customer in Customer.objects.all().iterator():
        tags_str = customer.tags_old or ""
        tags_list = [t.strip() for t in tags_str.split(',') if t.strip()]
        customer.tags = tags_list
        customer.save()


def rollback_tags_to_string(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    for customer in Customer.objects.all().iterator():
        tags_list = customer.tags or []
        customer.tags_old = ",".join(tags_list)
        customer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('receptify', '0003_business_is_onboarding_dismissed_verificationtoken'),
        ('customers', '0002_alter_customer_custom_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('DROPDOWN', 'Dropdown'), ('MULTI_SELECT', 'Multi-select'), ('CURRENCY', 'Currency')], db_column='field_type', max_length=50)),
                ('is_required', models.BooleanField(db_column='is_required', default=False)),
                ('options', models.JSONField(blank=True, default=list, null=True)),
                ('group_name', models.CharField(blank=True, db_column='group_name', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'custom_field_definitions',
            },
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='tags',
            new_name='tags_old',
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.RunPython(migrate_tags_to_array, rollback_tags_to_string),
        migrations.RemoveField(
            model_name='customer',
            name='tags_old',
        ),
        migrations.AddIndex(
            model_name='customer',
            index=django.contrib.postgres.indexes.GinIndex(fields=['custom_fields'], name='customers_custom_fields_gin', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='customers_tags_gin'),
        ),
        migrations.AddField(
            model_name='customfielddefinition',
            name='business',
            field=models.ForeignKey(db_column='business_id', on_delete=django.db.models.deletion.CASCADE, to='receptify.business'),
        ),
        migrations.AlterUniqueTogether(
            name='customfielddefinition',
            unique_together={('business', 'key')},
        ),
    ]
