# Generated by Django 4.2.30 on 2026-07-03 16:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptify', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('purpose', models.CharField(default='custom', max_length=255)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('language', models.CharField(default='en', max_length=50)),
                ('voice_type', models.CharField(default='female_professional', max_length=100)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('calling_window_start', models.CharField(default='09:00', max_length=10)),
                ('calling_window_end', models.CharField(default='19:00', max_length=10)),
                ('retry_attempts', models.IntegerField(default=2)),
                ('delay_between_calls', models.IntegerField(default=5)),
                ('script_text', models.TextField(blank=True, null=True)),
                ('compliance_confirmed', models.BooleanField(default=False)),
                ('total_contacts', models.IntegerField(default=0)),
                ('calls_completed', models.IntegerField(default=0)),
                ('calls_answered', models.IntegerField(default=0)),
                ('calls_failed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_type', models.IntegerField(default=0)),
                ('business', models.ForeignKey(db_column='business_id', on_delete=django.db.models.deletion.CASCADE, to='receptify.business')),
            ],
            options={
                'db_table': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('language', models.CharField(default='en', max_length=50)),
                ('preview', models.TextField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'templates',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('purpose', models.CharField(default='custom', max_length=255)),
                ('language', models.CharField(default='en', max_length=50)),
                ('body', models.TextField()),
                ('tone', models.CharField(default='professional', max_length=100)),
                ('short_version', models.TextField(blank=True, null=True)),
                ('polite_version', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(db_column='business_id', on_delete=django.db.models.deletion.CASCADE, to='receptify.business')),
            ],
            options={
                'db_table': 'scripts',
            },
        ),
        migrations.CreateModel(
            name='CampaignCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(db_column='campaign_id', on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'db_table': 'campaign_customers',
                'unique_together': {('campaign', 'customer')},
            },
        ),
    ]
