# Generated by Django 4.2.30 on 2026-07-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='compliance_confirmed',
            field=models.BooleanField(db_column='compliance_confirmed', default=False),
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='compliance_confirmed',
            new_name='is_compliance_confirmed',
        ),
    ]
