# Generated by Django 4.2.30 on 2026-07-08 16:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_compliance_confirmed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignFilterGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logic_operator', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], db_column='logic_operator', default='AND', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(db_column='campaign_id', on_delete=django.db.models.deletion.CASCADE, related_name='filter_groups', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'campaign_filter_groups',
            },
        ),
        migrations.CreateModel(
            name='CampaignFilterRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(db_column='field_name', max_length=100)),
                ('operator', models.CharField(db_column='operator', max_length=50)),
                ('value', models.JSONField(db_column='value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='campaigns.campaignfiltergroup')),
            ],
            options={
                'db_table': 'campaign_filter_rules',
            },
        ),
    ]
