# Generated by Django 4.2.30 on 2026-07-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaignfiltergroup_campaignfilterrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignfiltergroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='campaignfilterrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
