# Generated by Django 4.2.30 on 2026-07-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(db_column='email_verified', default=False),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email_verified',
            new_name='is_email_verified',
        ),
    ]
