# Generated by Django 4.2.30 on 2026-07-05 09:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('receptify', '0002_alter_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_onboarding_dismissed',
            field=models.BooleanField(db_column='onboarding_dismissed', default=False),
        ),
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='receptify.user')),
            ],
            options={
                'db_table': 'verification_tokens',
            },
        ),
    ]
